[mcp_servers.WolframLanguage]
command = "/Applications/Wolfram.app/Contents/MacOS/wolfram"
args = ["-run", "PacletSymbol[\"Wolfram/AgentTools\",\"Wolfram`AgentTools`StartMCPServer\"][]", "-noinit", "-noprompt"]
env = { MCP_SERVER_NAME = "WolframLanguage", WOLFRAM_BASE = "/Library/Wolfram", WOLFRAM_USERBASE = "/Users/Reiko/Library/Wolfram", WOLFRAM_LOCALBASE = "/Users/Reiko/Library/Wolfram/Objects" }
enabled = true

[mcp_servers.WolframLanguage.tools.WolframLanguageContext]
approval_mode = "approve"

[mcp_servers.WolframLanguage.tools.WolframLanguageEvaluator]
approval_mode = "approve"

[mcp_servers.WolframLanguage.tools.CodeInspector]
approval_mode = "approve"
